# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gaiasdk/plugin.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14gaiasdk/plugin.proto\x12\x05proto\"\x9d\x01\n\x03Job\x12\x11\n\tunique_id\x18\x01 \x01(\r\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x11\n\tdependson\x18\x04 \x03(\r\x12\x1d\n\x04\x61rgs\x18\x05 \x03(\x0b\x32\x0f.proto.Argument\x12-\n\x0binteraction\x18\x06 \x01(\x0b\x32\x18.proto.ManualInteraction\"I\n\x08\x41rgument\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0b\n\x03key\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\t\"E\n\x11ManualInteraction\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"V\n\tJobResult\x12\x11\n\tunique_id\x18\x01 \x01(\r\x12\x0e\n\x06\x66\x61iled\x18\x02 \x01(\x08\x12\x15\n\rexit_pipeline\x18\x03 \x01(\x08\x12\x0f\n\x07message\x18\x04 \x01(\t\"\x07\n\x05\x45mpty2[\n\x06Plugin\x12%\n\x07GetJobs\x12\x0c.proto.Empty\x1a\n.proto.Job0\x01\x12*\n\nExecuteJob\x12\n.proto.Job\x1a\x10.proto.JobResultB%\n\x15io.gaiapipeline.protoB\nGRPCPluginP\x01\x62\x06proto3')



_JOB = DESCRIPTOR.message_types_by_name['Job']
_ARGUMENT = DESCRIPTOR.message_types_by_name['Argument']
_MANUALINTERACTION = DESCRIPTOR.message_types_by_name['ManualInteraction']
_JOBRESULT = DESCRIPTOR.message_types_by_name['JobResult']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
Job = _reflection.GeneratedProtocolMessageType('Job', (_message.Message,), {
  'DESCRIPTOR' : _JOB,
  '__module__' : 'gaiasdk.plugin_pb2'
  # @@protoc_insertion_point(class_scope:proto.Job)
  })
_sym_db.RegisterMessage(Job)

Argument = _reflection.GeneratedProtocolMessageType('Argument', (_message.Message,), {
  'DESCRIPTOR' : _ARGUMENT,
  '__module__' : 'gaiasdk.plugin_pb2'
  # @@protoc_insertion_point(class_scope:proto.Argument)
  })
_sym_db.RegisterMessage(Argument)

ManualInteraction = _reflection.GeneratedProtocolMessageType('ManualInteraction', (_message.Message,), {
  'DESCRIPTOR' : _MANUALINTERACTION,
  '__module__' : 'gaiasdk.plugin_pb2'
  # @@protoc_insertion_point(class_scope:proto.ManualInteraction)
  })
_sym_db.RegisterMessage(ManualInteraction)

JobResult = _reflection.GeneratedProtocolMessageType('JobResult', (_message.Message,), {
  'DESCRIPTOR' : _JOBRESULT,
  '__module__' : 'gaiasdk.plugin_pb2'
  # @@protoc_insertion_point(class_scope:proto.JobResult)
  })
_sym_db.RegisterMessage(JobResult)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'gaiasdk.plugin_pb2'
  # @@protoc_insertion_point(class_scope:proto.Empty)
  })
_sym_db.RegisterMessage(Empty)

_PLUGIN = DESCRIPTOR.services_by_name['Plugin']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025io.gaiapipeline.protoB\nGRPCPluginP\001'
  _JOB._serialized_start=32
  _JOB._serialized_end=189
  _ARGUMENT._serialized_start=191
  _ARGUMENT._serialized_end=264
  _MANUALINTERACTION._serialized_start=266
  _MANUALINTERACTION._serialized_end=335
  _JOBRESULT._serialized_start=337
  _JOBRESULT._serialized_end=423
  _EMPTY._serialized_start=425
  _EMPTY._serialized_end=432
  _PLUGIN._serialized_start=434
  _PLUGIN._serialized_end=525
# @@protoc_insertion_point(module_scope)
